package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var generateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate asset skeletons and templates",
	Long:  "Generate asset skeletons for scripts, scenes, atlases, and other game assets",
}

var generateScriptCmd = &cobra.Command{
	Use:   "script [name]",
	Short: "Generate a new script asset",
	Long:  "Generate a new TypeScript script with its corresponding .script.json manifest",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		name := args[0]
		outputDir, _ := cmd.Flags().GetString("output")
		if outputDir == "" {
			outputDir = "assets/scripts"
		}

		if err := generateScript(name, outputDir); err != nil {
			fmt.Printf("Error generating script: %s\n", err)
			os.Exit(1)
		}

		fmt.Printf("Generated script: %s/%s.ts and %s/%s.script.json\n", outputDir, name, outputDir, name)
	},
}

var generateSceneCmd = &cobra.Command{
	Use:   "scene [name]",
	Short: "Generate a new scene asset",
	Long:  "Generate a new scene JSON file with basic structure",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		name := args[0]
		outputDir, _ := cmd.Flags().GetString("output")
		if outputDir == "" {
			outputDir = "scenes"
		}

		if err := generateScene(name, outputDir); err != nil {
			fmt.Printf("Error generating scene: %s\n", err)
			os.Exit(1)
		}

		fmt.Printf("Generated scene: %s/%s.scene.json\n", outputDir, name)
	},
}

var generateAtlasCmd = &cobra.Command{
	Use:   "atlas [name]",
	Short: "Generate a new sprite atlas configuration",
	Long:  "Generate a new sprite atlas configuration file",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		name := args[0]
		outputDir, _ := cmd.Flags().GetString("output")
		if outputDir == "" {
			outputDir = "assets/atlases"
		}

		if err := generateAtlas(name, outputDir); err != nil {
			fmt.Printf("Error generating atlas: %s\n", err)
			os.Exit(1)
		}

		fmt.Printf("Generated atlas config: %s/%s.atlas.json\n", outputDir, name)
	},
}

var generateManifestCmd = &cobra.Command{
	Use:   "manifest [name]",
	Short: "Generate a new game manifest",
	Long:  "Generate a new .jm.json game manifest file",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		name := args[0]
		outputPath, _ := cmd.Flags().GetString("output")
		if outputPath == "" {
			outputPath = ".jm.json"
		}

		if err := generateManifest(name, outputPath); err != nil {
			fmt.Printf("Error generating manifest: %s\n", err)
			os.Exit(1)
		}

		fmt.Printf("Generated manifest: %s\n", outputPath)
	},
}

func init() {
	generateScriptCmd.Flags().StringP("output", "o", "", "Output directory for the script (default: assets/scripts)")
	generateSceneCmd.Flags().StringP("output", "o", "", "Output directory for the scene (default: scenes)")
	generateAtlasCmd.Flags().StringP("output", "o", "", "Output directory for the atlas (default: assets/atlases)")
	generateManifestCmd.Flags().StringP("output", "o", ".jm.json", "Output path for the manifest (default: .jm.json)")

	generateCmd.AddCommand(generateScriptCmd)
	generateCmd.AddCommand(generateSceneCmd)
	generateCmd.AddCommand(generateAtlasCmd)
	generateCmd.AddCommand(generateManifestCmd)
}

func generateScript(name, outputDir string) error {
	// Sanitize name
	name = strings.ToLower(strings.ReplaceAll(name, " ", "_"))

	// Create output directory
	if err := os.MkdirAll(outputDir, os.ModePerm); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Generate TypeScript file
	tsPath := filepath.Join(outputDir, name+".ts")
	tsContent := fmt.Sprintf(`// %s script
// Generated by Journeyman CLI

let t: f32 = 0;

export function onUpdate(dt: f32): void {
    t += dt;
}

export function onStart(): void {
    // Initialize script here
}
`, strings.Title(strings.ReplaceAll(name, "_", " ")))

	if err := os.WriteFile(tsPath, []byte(tsContent), 0644); err != nil {
		return fmt.Errorf("failed to write TypeScript file: %w", err)
	}

	// Generate script manifest
	manifestPath := filepath.Join(outputDir, name+".script.json")
	manifestContent := fmt.Sprintf(`{
  "name": "%s",
  "script": "%s/%s.ts",
  "binary": "%s/%s.wasm"
}
`, strings.Title(strings.ReplaceAll(name, "_", " ")), outputDir, name, outputDir, name)

	if err := os.WriteFile(manifestPath, []byte(manifestContent), 0644); err != nil {
		return fmt.Errorf("failed to write script manifest: %w", err)
	}

	return nil
}

func generateScene(name, outputDir string) error {
	// Sanitize name
	name = strings.ToLower(strings.ReplaceAll(name, " ", "_"))

	// Create output directory
	if err := os.MkdirAll(outputDir, os.ModePerm); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Generate scene JSON
	scenePath := filepath.Join(outputDir, name+".scene.json")
	sceneContent := fmt.Sprintf(`{
  "name": "%s",
  "entities": [
    {
      "name": "Example Entity",
      "components": {
        "ScriptComponent": {
          "script": "assets/scripts/example"
        }
      }
    }
  ]
}
`, strings.Title(strings.ReplaceAll(name, "_", " ")))

	if err := os.WriteFile(scenePath, []byte(sceneContent), 0644); err != nil {
		return fmt.Errorf("failed to write scene file: %w", err)
	}

	return nil
}

func generateAtlas(name, outputDir string) error {
	// Sanitize name
	name = strings.ToLower(strings.ReplaceAll(name, " ", "_"))

	// Create output directory
	if err := os.MkdirAll(outputDir, os.ModePerm); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Generate atlas configuration
	atlasPath := filepath.Join(outputDir, name+".atlas.json")
	atlasContent := fmt.Sprintf(`{
  "name": "%s",
  "output": "assets/atlases/%s.png",
  "outputMetadata": "assets/atlases/%s.atlas.json",
  "maxSize": 2048,
  "padding": 2,
  "sprites": [
    {
      "name": "sprite1",
      "path": "assets/sprites/sprite1.png"
    }
  ]
}
`, strings.Title(strings.ReplaceAll(name, "_", " ")), name, name)

	if err := os.WriteFile(atlasPath, []byte(atlasContent), 0644); err != nil {
		return fmt.Errorf("failed to write atlas config: %w", err)
	}

	return nil
}

func generateManifest(name, outputPath string) error {
	// Sanitize name
	gameName := strings.Title(strings.ReplaceAll(name, "_", " "))

	// Generate manifest JSON
	manifestContent := fmt.Sprintf(`{
  "name": "%s",
  "version": "0.1.0",
  "engine": "../build/engine/journeyman_engine",
  "entryScene": "scenes/level1.scene.json",
  "scenes": [
    "scenes/level1.scene.json"
  ],
  "assets": [
  ]
}
`, gameName)

	if err := os.WriteFile(outputPath, []byte(manifestContent), 0644); err != nil {
		return fmt.Errorf("failed to write manifest file: %w", err)
	}

	return nil
}
